### ISSUE TITLE
Calculation of medianconversion factors

### ISSUE THREAD

**Issue by Gregor0815** [EuropeanForestInstitute/tradeflows#2]
In order to understand all steps in quantity calculation, I rebuilt the medianconversion factor calculation. I was aming for the same results.
But unfortunately I didn't get them. After little investigation I figured out that in your calculation conversion factors replaced by inf (division by zero) are not removed before calculating the median. Why are those values beeing kept, what is the idea behind that? Or is it simply a bug?

best regards

**Comment by paul4forest** [comment]
Fixed in [this commit](https://github.com/EuropeanForestInstitute/tradeflows/commit/30e97f861678995ade56cd554f39860c5677aca9#diff-4d759ec0d2176fb116d34e43bde3bec2R197) by removing Inf values from the calculation. 

But this problem of conversion factors equal to Inf would be better solved earlier by changing 0 quantities to NA values. In other words, a zero quantity doesn't make sense, it should be replaced by a missing value. This might be done in an earlier stage. I'll mark this issue as solved for now.

**Comment by paul4forest** [comment]
Fixed in [this commit](https://github.com/EuropeanForestInstitute/tradeflows/commit/30e97f861678995ade56cd554f39860c5677aca9#diff-4d759ec0d2176fb116d34e43bde3bec2R197) by removing Inf values from the calculation. 

But this problem of conversion factors equal to Inf would be better solved earlier by changing 0 quantities to NA values. In other words, a zero quantity doesn't make sense, it should be replaced by a missing value. This might be done in an earlier stage. I'll mark this issue as solved for now.

**Comment by Gregor0815** [comment]
As it is the same topic, I just want to mention that 0 conversion factors exists as well (due to 0 weight) in medianconversion factor calculation. If inf values are removed, 0 values should be removed too - I would consider it just as the same problem.

**Comment by paul4forest** [comment]
Correct, I have removed 0 and Inf values from the conversion factor calculation in commit 3e91a1d716.
I have also added [a unit test](https://github.com/EuropeanForestInstitute/tradeflows/commit/3e91a1d716ec797a00e537226c9dae7cc21f2ac1#diff-bff01675ad37fb59abd2accd5a14f490R88).
